# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '图片轮播器' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 图片轮播器
pod 'SDWebImage', '~> 4.0.0-beta2'
  target '图片轮播器Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '图片轮播器UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
